tt = read.csv('trial_type.csv')
fe = read.csv('trial_final_errors.csv')
w = read.csv('trial_magnitudes.csv')
d = data.frame(trial_type=tt$trial_type,weight=w$weight_magnitudes,final_error=fe$final_error)
d$trial_type = factor(d$trial_type)
str(d)
levels(d$trial_type) = c('easy','hard')
mod0 = lm(data=d,final_error ~ trial_type)
summary(mod0)
mod1 = lm(data=d,final_error ~ trial_type + weight)
summary(mod1)
library(ggplot2)
ggplot(data=d,aes(x=weight,y=final_error,color=trial_type)) + geom_scatter()
ggplot(data=d,aes(x=weight,y=final_error,color=trial_type)) + geom_point()